name: Generic CI/CD Example

on: 
  workflow_call:
  
jobs:
 tflint:
    uses: ./.github/workflows/tflint.yaml
    with:
      working-directory: .
    secrets: 
      repo_token: ${{ secrets.GITHUB_TOKEN }}
  